name: WordPress Coding Standards (WPCS)

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  lint:
    name: PHP CodeSniffer Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs -n